#! /bin/sh
# /*@@
#   @file      linux-gnu
#   @date      Thu Feb 25 09:53:22 1999
#   @author    Tom Goodale
#   @desc 
#   
#   @enddesc 
#   @version $Header: /cactus/Cactus/lib/make/known-architectures/linux-gnu,v 1.7 1999/07/15 20:08:36 goodale Exp $
# @@*/

. $srcdir/known-architectures/linux
