#! /bin/sh
#  /*@@
#    @file      linux-gnulibc1
#    @date      Thu Apr 1 1999
#    @author    Gabrielle Allen
#    @desc 
#   
#    @enddesc
#    @version $Header: /cactus/Cactus/lib/make/known-architectures/linux-gnulibc1,v 1.2 1999/07/15 20:08:36 goodale Exp $
#  @@*/

. $srcdir/known-architectures/linux
