#! /bin/sh
# /*@@
#   @file      linux-gnu
#   @date      Thu Feb 25 09:53:22 1999
#   @author    Tom Goodale
#   @desc 
#   
#   @enddesc 
#   @version $Header: /cactus/Cactus/lib/make/known-architectures/linux-gnuaout,v 1.1 1999/09/04 19:20:56 goodale Exp $
# @@*/

. $srcdir/known-architectures/linux
