#! /bin/sh
# /*@@
#   @file      CUSTOM
#   @date      Wed Jul 21 13:27:07 1999
#   @author    Tom Goodale
#   @desc 
#   
#   @enddesc
#   @version $Header: /cactus/Cactus/lib/make/extras/MPI/CUSTOM,v 1.1 1999/07/21 12:25:01 goodale Exp $ 
# @@*/


# Allow the user to completely specify at the command line,
echo "Custom MPI selected"

MPI_LIBS="$MPI_LIBS" 
MPI_LIB_DIRS="$MPI_LIB_DIRS"
MPI_INC_DIRS="$MPI_INC_DIRS"

