#! /bin/sh
# /*@@
#   @file      NATIVE
#   @date      Wed Jul 21 13:27:07 1999
#   @author    Tom Goodale
#   @desc 
#   
#   @enddesc
#   @version $Header: /cactus/Cactus/lib/make/extras/MPI/NATIVE,v 1.3 2000/04/04 10:01:33 tradke Exp $ 
# @@*/

echo "Native MPI selected"

# This should be filled out by the know-architecture stuff.

if test -z "$NATIVE_MPI_LIBS" ; then
  echo "ERROR: NATIVE MPI selected, but this architecture has no native MPI"
  exit 2
fi

MPI_LIBS=$NATIVE_MPI_LIBS
MPI_LIB_DIRS=${NATIVE_MPI_LIB_DIRS:-""}
MPI_INC_DIRS=${NATIVE_MPI_INC_DIRS:-""}
