#define DECLARE_CCTK_PARAMETERS \
CCTK_STRING  method&&\
COMMON /benchadmrest/method&&\
CCTK_STRING  bound&&\
CCTK_INT time_symmetric&&\
COMMON /BenchADMpriv/bound,time_symmetric&&\
CCTK_REAL  CCTKH2&&\
CCTK_REAL  CCTKH3&&\
CCTK_REAL  CCTKH8&&\
CCTK_REAL  CCTKH11&&\
CCTK_REAL  CCTKH12&&\
CCTK_STRING  CCTKH0&&\
CCTK_STRING  evolution_system&&\
CCTK_STRING  CCTKH4&&\
CCTK_STRING  CCTKH5&&\
CCTK_STRING  CCTKH6&&\
CCTK_STRING  CCTKH7&&\
CCTK_STRING  CCTKH14&&\
CCTK_STRING  slicing&&\
CCTK_STRING  CCTKH15&&\
CCTK_INT CCTKH1&&\
CCTK_INT CCTKH9&&\
CCTK_INT CCTKH10&&\
CCTK_INT CCTKH13&&\
CCTK_INT CCTKH16&&\
CCTK_INT CCTKH17&&\
CCTK_INT CCTKH18&&\
COMMON /EINSTEINrest/CCTKH2,CCTKH3,CCTKH8,CCTKH11,CCTKH12,CCTKH0,evolution_system,CCTKH4,CCTKH5,CCTKH6,CCTKH7,CCTKH14,slicing,CCTKH15,CCTKH1,CCTKH9,CCTKH10,CCTKH13,CCTKH16,CCTKH17,CCTKH18&&\
CCTK_STRING  timestep_method&&\
CCTK_INT timestep_outonly&&\
COMMON /TIMErest/timestep_method,timestep_outonly&&\


