/* Defines for active thorns in the code. */

#define CACTUSBASE_CARTGRID3D
#define CACTUSBASE_TIME
#define CACTUSPUGH_PUGHSLAB
#define CACTUSEINSTEIN_EINSTEIN
#define CACTUSBENCH_BENCHADM
#define CACTUSPUGH_PUGH
#define CACTUSPUGH_PUGHREDUCE
#define CACTUSBASE_BOUNDARY
#define CACTUSBASE_IOBASIC
#define CACTUSEINSTEIN_IDLINEARWAVES
#define CACTUSBASE_IOUTIL
#define CACTUSBASE_IOASCII


