#define DECLARE_CCTK_PARAMETERS \
CCTK_REAL  out_xline_y&&\
CCTK_REAL  out_xline_z&&\
CCTK_REAL  out_xyplane_z&&\
CCTK_REAL  out_xzplane_y&&\
CCTK_REAL  out_yline_x&&\
CCTK_REAL  out_yline_z&&\
CCTK_REAL  out_yzplane_x&&\
CCTK_REAL  out_zline_x&&\
CCTK_REAL  out_zline_y&&\
CCTK_STRING  checkpoint_ID_file&&\
CCTK_STRING  checkpoint_dir&&\
CCTK_STRING  checkpoint_file&&\
CCTK_STRING  newverbose&&\
CCTK_STRING  out3D_mode&&\
CCTK_STRING  out_fileinfo&&\
CCTK_STRING  outdir&&\
CCTK_STRING  parfile_name&&\
CCTK_STRING  parfile_write&&\
CCTK_STRING  recover&&\
CCTK_STRING  recover_ID_files&&\
CCTK_STRING  recover_ID_vars&&\
CCTK_STRING  recover_file&&\
CCTK_STRING  recovery_dir&&\
CCTK_INT checkpoint_ID&&\
CCTK_INT checkpoint_every&&\
CCTK_INT checkpoint_keep&&\
CCTK_INT checkpoint_keep_all&&\
CCTK_INT checkpoint_on_terminate&&\
CCTK_INT new_filename_scheme&&\
CCTK_INT out3D_downsample_x&&\
CCTK_INT out3D_downsample_y&&\
CCTK_INT out3D_downsample_z&&\
CCTK_INT out3D_parameters&&\
CCTK_INT out3D_procs&&\
CCTK_INT out3D_septimefiles&&\
CCTK_INT out3D_single&&\
CCTK_INT out3D_unchunked&&\
CCTK_INT out_every&&\
CCTK_INT out_xline_yi&&\
CCTK_INT out_xline_zi&&\
CCTK_INT out_xyplane_zi&&\
CCTK_INT out_xzplane_yi&&\
CCTK_INT out_yline_xi&&\
CCTK_INT out_yline_zi&&\
CCTK_INT out_yzplane_xi&&\
CCTK_INT out_zline_xi&&\
CCTK_INT out_zline_yi&&\
CCTK_INT parfile_update_every&&\
CCTK_INT print_timing_info&&\
CCTK_INT recover_and_remove&&\
CCTK_INT verbose&&\
COMMON /IOrest/out_xline_y,out_xline_z,out_xyplane_z,out_xzplane_y,out_yline_x,out_yline_z,out_yzplane_x,out_zline_x,out_zline_y,checkpoint_ID_file,checkpoint_dir,checkpoint_file,newverbose,out3D_mode,out_fileinfo,outdir,parfile_name,parfile_write,recover,recover_ID_files,recover_ID_vars,recover_file,recovery_dir,checkpoint_ID,checkpoint_every,checkpoint_keep,checkpoint_keep_all,checkpoint_on_terminate,new_filename_scheme,out3D_downsample_x,out3D_downsample_y,out3D_downsample_z,out3D_parameters,out3D_procs,out3D_septimefiles,out3D_single,out3D_unchunked,out_every,out_xline_yi,out_xline_zi,out_xyplane_zi,out_xzplane_yi,out_yline_xi,out_yline_zi,out_yzplane_xi,out_zline_xi,out_zline_yi,parfile_update_every,print_timing_info,recover_and_remove,verbose&&\


