#ifndef _CCTKI_VERSION_H_
#define _CCTKI_VERSION_H_
#define CCTK_VERSION_MAJOR 4
#define CCTK_VERSION_MINOR 0
#define CCTK_VERSION_OTHER b11
#define CCTK_VERSION       4.0.b11
#endif /* _CCTKI_VERSION_H_*/
