#define DECLARE_CCTK_PARAMETERS \
CCTK_REAL  gaussian_amplitude&&\
CCTK_REAL  gaussian_sigma2&&\
CCTK_REAL  psiminustwo_cut&&\
CCTK_REAL  rot_shift_att_sigma&&\
CCTK_REAL  rotation_omega&&\
CCTK_STRING  advection&&\
CCTK_STRING  evolution_system&&\
CCTK_STRING  initial_data&&\
CCTK_STRING  initial_lapse&&\
CCTK_STRING  initial_shift&&\
CCTK_STRING  mixed_slicing&&\
CCTK_STRING  shift&&\
CCTK_STRING  slicing&&\
CCTK_STRING  slicing_verbose&&\
CCTK_INT einstein_register_slicing&&\
CCTK_INT rot_shift_att&&\
CCTK_INT rot_shift_att_pow&&\
CCTK_INT rotation_psipower&&\
CCTK_INT use_conformal&&\
CCTK_INT use_conformal_derivs&&\
CCTK_INT use_mask&&\
COMMON /einsteinrest/gaussian_amplitude,gaussian_sigma2,psiminustwo_cut,rot_shift_att_sigma,rotation_omega,advection,evolution_system,initial_data,initial_lapse,initial_shift,mixed_slicing,shift,slicing,slicing_verbose,einstein_register_slicing,rot_shift_att,rot_shift_att_pow,rotation_psipower,use_conformal,use_conformal_derivs,use_mask&&\
CCTK_REAL  dtfac&&\
CCTK_REAL  gauge_speed&&\
CCTK_STRING  wavecalc&&\
CCTK_INT conformal_storage_all&&\
CCTK_INT rsquared_in_sphm&&\
COMMON /Einsteinpriv/dtfac,gauge_speed,wavecalc,conformal_storage_all,rsquared_in_sphm&&\
CCTK_REAL  CCTKH1&&\
CCTK_REAL  CCTKH2&&\
CCTK_REAL  CCTKH3&&\
CCTK_REAL  CCTKH4&&\
CCTK_REAL  CCTKH13&&\
CCTK_REAL  CCTKH14&&\
CCTK_REAL  CCTKH15&&\
CCTK_REAL  CCTKH16&&\
CCTK_REAL  CCTKH17&&\
CCTK_REAL  CCTKH18&&\
CCTK_REAL  CCTKH19&&\
CCTK_REAL  CCTKH20&&\
CCTK_STRING  CCTKH0&&\
CCTK_STRING  domain&&\
CCTK_STRING  CCTKH5&&\
CCTK_STRING  CCTKH12&&\
CCTK_INT CCTKH6&&\
CCTK_INT CCTKH7&&\
CCTK_INT CCTKH8&&\
CCTK_INT CCTKH9&&\
CCTK_INT CCTKH10&&\
CCTK_INT CCTKH11&&\
COMMON /GRIDrest/CCTKH1,CCTKH2,CCTKH3,CCTKH4,CCTKH13,CCTKH14,CCTKH15,CCTKH16,CCTKH17,CCTKH18,CCTKH19,CCTKH20,CCTKH0,domain,CCTKH5,CCTKH12,CCTKH6,CCTKH7,CCTKH8,CCTKH9,CCTKH10,CCTKH11&&\
CCTK_STRING  timestep_method&&\
CCTK_INT CCTKH21&&\
COMMON /TIMErest/timestep_method,CCTKH21&&\


