#define DECLARE_CCTK_PARAMETERS \
CCTK_REAL  out1D_xline_y&&\
CCTK_REAL  out1D_xline_z&&\
CCTK_REAL  out1D_yline_x&&\
CCTK_REAL  out1D_yline_z&&\
CCTK_REAL  out1D_zline_x&&\
CCTK_REAL  out1D_zline_y&&\
CCTK_REAL  out2D_xyplane_z&&\
CCTK_REAL  out2D_xzplane_y&&\
CCTK_REAL  out2D_yzplane_x&&\
CCTK_STRING  out1D_style&&\
CCTK_STRING  out1D_vars&&\
CCTK_STRING  out2D_style&&\
CCTK_STRING  out2D_vars&&\
CCTK_STRING  out3D_style&&\
CCTK_STRING  out3D_vars&&\
CCTK_STRING  out_format&&\
CCTK_STRING  out_style&&\
CCTK_STRING  outdir1D&&\
CCTK_STRING  outdir2D&&\
CCTK_STRING  outdir3D&&\
CCTK_INT out1D_d&&\
CCTK_INT out1D_every&&\
CCTK_INT out1D_x&&\
CCTK_INT out1D_xline_yi&&\
CCTK_INT out1D_xline_zi&&\
CCTK_INT out1D_y&&\
CCTK_INT out1D_yline_xi&&\
CCTK_INT out1D_yline_zi&&\
CCTK_INT out1D_z&&\
CCTK_INT out1D_zline_xi&&\
CCTK_INT out1D_zline_yi&&\
CCTK_INT out2D_every&&\
CCTK_INT out2D_xyplane_zi&&\
CCTK_INT out2D_xzplane_yi&&\
CCTK_INT out2D_yzplane_xi&&\
CCTK_INT out3D_every&&\
COMMON /IOASCIIpriv/out1D_xline_y,out1D_xline_z,out1D_yline_x,out1D_yline_z,out1D_zline_x,out1D_zline_y,out2D_xyplane_z,out2D_xzplane_y,out2D_yzplane_x,out1D_style,out1D_vars,out2D_style,out2D_vars,out3D_style,out3D_vars,out_format,out_style,outdir1D,outdir2D,outdir3D,out1D_d,out1D_every,out1D_x,out1D_xline_yi,out1D_xline_zi,out1D_y,out1D_yline_xi,out1D_yline_zi,out1D_z,out1D_zline_xi,out1D_zline_yi,out2D_every,out2D_xyplane_zi,out2D_xzplane_yi,out2D_yzplane_xi,out3D_every&&\
CCTK_REAL  out_xline_y&&\
CCTK_REAL  out_xline_z&&\
CCTK_REAL  out_xyplane_z&&\
CCTK_REAL  out_xzplane_y&&\
CCTK_REAL  out_yline_x&&\
CCTK_REAL  out_yline_z&&\
CCTK_REAL  out_yzplane_x&&\
CCTK_REAL  out_zline_x&&\
CCTK_REAL  out_zline_y&&\
CCTK_STRING  CCTKH1&&\
CCTK_STRING  CCTKH2&&\
CCTK_STRING  CCTKH4&&\
CCTK_STRING  newverbose&&\
CCTK_STRING  CCTKH11&&\
CCTK_STRING  out_fileinfo&&\
CCTK_STRING  outdir&&\
CCTK_STRING  CCTKH17&&\
CCTK_STRING  CCTKH19&&\
CCTK_STRING  CCTKH21&&\
CCTK_STRING  CCTKH22&&\
CCTK_STRING  CCTKH23&&\
CCTK_STRING  CCTKH25&&\
CCTK_STRING  CCTKH26&&\
CCTK_INT CCTKH0&&\
CCTK_INT CCTKH3&&\
CCTK_INT CCTKH5&&\
CCTK_INT CCTKH6&&\
CCTK_INT CCTKH7&&\
CCTK_INT new_filename_scheme&&\
CCTK_INT CCTKH8&&\
CCTK_INT CCTKH9&&\
CCTK_INT CCTKH10&&\
CCTK_INT CCTKH12&&\
CCTK_INT CCTKH13&&\
CCTK_INT CCTKH14&&\
CCTK_INT CCTKH15&&\
CCTK_INT CCTKH16&&\
CCTK_INT out_every&&\
CCTK_INT out_xline_yi&&\
CCTK_INT out_xline_zi&&\
CCTK_INT out_xyplane_zi&&\
CCTK_INT out_xzplane_yi&&\
CCTK_INT out_yline_xi&&\
CCTK_INT out_yline_zi&&\
CCTK_INT out_yzplane_xi&&\
CCTK_INT out_zline_xi&&\
CCTK_INT out_zline_yi&&\
CCTK_INT CCTKH18&&\
CCTK_INT CCTKH20&&\
CCTK_INT CCTKH24&&\
CCTK_INT verbose&&\
COMMON /IOrest/out_xline_y,out_xline_z,out_xyplane_z,out_xzplane_y,out_yline_x,out_yline_z,out_yzplane_x,out_zline_x,out_zline_y,CCTKH1,CCTKH2,CCTKH4,newverbose,CCTKH11,out_fileinfo,outdir,CCTKH17,CCTKH19,CCTKH21,CCTKH22,CCTKH23,CCTKH25,CCTKH26,CCTKH0,CCTKH3,CCTKH5,CCTKH6,CCTKH7,new_filename_scheme,CCTKH8,CCTKH9,CCTKH10,CCTKH12,CCTKH13,CCTKH14,CCTKH15,CCTKH16,out_every,out_xline_yi,out_xline_zi,out_xyplane_zi,out_xzplane_yi,out_yline_xi,out_yline_zi,out_yzplane_xi,out_zline_xi,out_zline_yi,CCTKH18,CCTKH20,CCTKH24,verbose&&\


